services:
  unifi-cam-driveway:
    container_name: unifi-cam-driveway
    restart: unless-stopped
    build: .
    environment:
      - TZ=America/Toronto
    volumes:
      - "./client.pem:/client.pem"
      - "./unifi:/app/unifi"
    command: >-
      unifi-cam-proxy
      --verbose
      --host 192.168.1.1
      --mac 'AA:BB:CC:33:44:CC'
      --ip 192.168.1.42
      --cert /client.pem
      --token "FrZnnUqOlO84CmQijsWjKiBBtDwoz7i4"
      --name "Driveway"
      --model "UVC G4 Dome"
      --fw-version "5.3.95"
      frigate
      --timestamp-modifier 90
      --snapshot-url "http://192.168.1.38:5050/api/driveway/latest.jpg"
      --ffmpeg-args='-c:v copy -c:a copy'
      --frigate-camera driveway
      --mqtt-host 192.168.1.3
      --mqtt-prefix fregate_flynn
      --frigate-http-url http://192.168.1.38:5050
      --frigate-time-sync-ms 1105
      --video1 rtsp://192.168.1.38:8554/driveway_src
      --video3 rtsp://192.168.1.38:8554/driveway_video3

# --ffmpeg-args='-c:v libx264 -preset veryfast -tune zerolatency -b:v 1200k -maxrate 2000k -bufsize 2400k -c:a aac -b:a 32k -ar 32000 -ac 1'

  unifi-cam-backyard:
    container_name: unifi-cam-backyard
    profiles: 
      - disabled
    restart: unless-stopped
    build: .
    environment:
      - TZ=America/Toronto
    volumes:
      - "./client.pem:/client.pem"
      - "./unifi:/app/unifi"
    command: >-
      unifi-cam-proxy
      --verbose
      --host 192.168.1.1
      --mac 'AA:BB:CC:33:44:99'
      --ip 192.168.254.4
      --cert /client.pem
      --token "GLuVqfAMLU8qjaXujLOCHxKQ7bXrdkic"
      --name "Canoe"
      --model "UVC G4 Dome"
      --fw-version "5.3.95"
      frigate
      --timestamp-modifier 90
      --snapshot-url "http://192.168.1.38:5050/api/backyard/latest.jpg"
      --ffmpeg-args='-c:v copy -c:a copy'
      --frigate-camera backyard
      --mqtt-host 192.168.1.3
      --mqtt-prefix fregate_flynn
      --frigate-http-url http://192.168.1.38:5050
      --frigate-time-sync-ms 1105
      --video1 rtsp://192.168.1.38:8554/backyard_src
      --video3 rtsp://192.168.1.38:8554/backyard_video3

  unifi-cam-canoe:
    profiles:
      - disabled
    container_name: unifi-cam-canoe
    restart: unless-stopped
    build: .
    volumes:
      - "./client.pem:/client.pem"
      - "./unifi:/app/unifi"
    command: >-
      unifi-cam-proxy
      --verbose
      --host 192.168.1.1
      --mac 'AA:BB:CC:33:44:99'
      --ip 192.168.254.4
      --cert /client.pem
      --token "GLuVqfAMLU8qjaXujLOCHxKQ7bXrdkic"
      --name "Canoe"
      --model "UVC G4 Dome"
      --fw-version "5.3.95"
      frigate
      --timestamp-modifier 90
      --snapshot-url "http://192.168.1.38:5050/api/canoe/latest.jpg"
      --ffmpeg-args='-c:v copy -c:a copy'
      --frigate-camera canoe
      --mqtt-host 192.168.1.3
      --mqtt-prefix fregate_flynn
      --frigate-http-url http://192.168.1.38:5050
      --frigate-time-sync-ms 1105
      --video1 rtsp://192.168.1.38:8554/canoe_src
      --video3 rtsp://192.168.1.38:8554/canoe_video3
#
  unifi-cam-side-door:
    container_name: unifi-cam-side-door
    restart: unless-stopped
    build: .
    volumes:
      - "./client.pem:/client.pem"
      - "./unifi:/app/unifi"
    command: >-
      unifi-cam-proxy
      --verbose
      --host 192.168.1.1
      --mac 'AA:BB:CC:33:44:BB'
      --ip 192.168.1.44
      --cert /client.pem
      --token "mZLBOQRasWKfnSOmLLr146bqMZMGeF85"
      --name "North Sidewalk"
      --model "UVC G4 Dome"
      --fw-version "5.3.95"
      frigate
      --timestamp-modifier 90
      --snapshot-url "http://192.168.1.38:5050/api/side_door/latest.jpg"
      --ffmpeg-args='-c:v copy -c:a copy'
      --frigate-camera side_door
      --mqtt-host 192.168.1.3
      --mqtt-prefix fregate_flynn
      --frigate-http-url http://192.168.1.38:5050
      --frigate-time-sync-ms 1105
      --video1 rtsp://192.168.1.38:8554/side_door_src
      --video3 rtsp://192.168.1.38:8554/side_door_video3

  unifi-cam-porch:
    container_name: unifi-cam-porch
    restart: unless-stopped
    build: .
    volumes:
      - "./client.pem:/client.pem"
      - "./unifi:/app/unifi"
    command: >-
      unifi-cam-proxy
      --verbose
      --host 192.168.1.1
      --mac 'AA:BB:CC:33:44:AA'
      --ip 192.168.1.45
      --cert /client.pem
      --token "duwm0lq2MXkyEqhMhMyDEellAHqIEh1O"
      --name "Porch"
      --model "UVC G4 Dome"
      --fw-version "5.3.95"
      frigate
      --timestamp-modifier 90
      --snapshot-url "http://192.168.1.38:5050/api/porch/latest.jpg"
      --ffmpeg-args='-c:v copy -c:a copy'
      --frigate-camera porch
      --mqtt-host 192.168.1.3
      --mqtt-prefix fregate_flynn
      --frigate-http-url http://192.168.1.38:5050
      --frigate-time-sync-ms 1105
      --video1 rtsp://192.168.1.38:8554/porch_src
      --video3 rtsp://192.168.1.38:8554/porch_video3
