services:
  unifi-cam:
    container_name: unifi-cam
    restart: unless-stopped
    build: .
    volumes:
      - "./client.pem:/client.pem"
      - "./unifi:/app/unifi"
    command: >-
      unifi-cam-proxy
      --verbose
      --host 192.168.1.1
      --mac 'AA:BB:CC:33:44:77'
      --ip 192.168.1.2
      --cert /client.pem
      --token "WakWvvTwFLc8QjU7i2pO6C3R9saKjGcA"
      --name "Side Door"
      frigate
      --timestamp-modifier 90
      --snapshot-url "http://192.168.1.3:5000/api/cam/latest.jpg"
      --ffmpeg-args='-c:v copy -c:a copy'
      --frigate-camera side_door
      --mqtt-host 192.168.1.3
      --mqtt-prefix frigate
      --frigate-http-url http://192.168.1.3:5000
      -s rtsp://192.168.1.2/cam